### ISSUE TITLE
How to visualize the gt_path in rviz?

### ISSUE THREAD

**Issue by Narla-Venkata-Anand-Sai-Kumar** [hoangvietdo/dero#2]

**Comment by hoangvietdo** [comment]
Hi,

Thank you for your interest in our work.

Currently, there is no option to visualize the ```gt_path``` in RViz. This feature may be added in the future. The delay is due to the fact that the provided ground truth is generated by a local navigation system (VINS), which needs to be aligned with the estimated path for a meaningful comparison.

Alternatively, if you just want to view the ```gt_path``` alongside the estimation without performing a comparison analysis, I recommend loading the ground truth ```csv``` file and the DeRO estimation ```txt``` file, and plotting them using another tool (e.g., MATLAB).

I hope this helps!
